### ISSUE TITLE
Can't get cells to size to appropriate height

### ISSUE THREAD

**Issue by gereons** [rwbutler/FlexibleRowHeightGridLayout#1]
Hi, I just came across this pod as I have a layout that requires side-by-side cells to have equal heights. Unfortunately I can't get it to work correctly, even in a simple examples where cells contain two labels of variably-sized text. For example, in this screenshot

![rowheight](https://user-images.githubusercontent.com/2861931/84275775-c67c3f00-ab31-11ea-8b1e-787160d35c52.png)

all cells starting from the 3rd row are way too small.

https://github.com/gereons/RowHeightTest contains a demo project that illustrates this.

Is this a bug, or am I using the pod incorrectly?

**Comment by rwbutler** [comment]
I think what you need here is to be able to calculate the height of a cell knowing that the width of that cell is fixed (because the columns will have a fixed width based on the number of columns you have specified there should be - in this case 2). Therefore rather than:

```swift
let size = cell.contentView.systemLayoutSizeFitting(
            UIView.layoutFittingCompressedSize,
            withHorizontalFittingPriority: .defaultHigh,
            verticalFittingPriority: .defaultLow
)
```

Try:

```swift
let size = cell.contentView.systemLayoutSizeFitting(
                   CGSize(width: layout.columnWidth(), height: UIView.noIntrinsicMetric),
                   withHorizontalFittingPriority: .required,
                   verticalFittingPriority: .defaultLow
)
```

This should calculate a size fitting the cell's constraints with the additional constraint that the width of the cell is fixed meaning that the height of the cell may now be accurately determined. Hope this helps!

**Comment by gereons** [comment]
Fantastic, that works exactly like I want it to. Thank you!

**Comment by rwbutler** [comment]
No problem - glad it helped! 🙂
